export enum ConfigEnums {
  'TICKET_PANEL_CHANNEL_ID' = 'TICKET_PANEL_CHANNEL_ID',
  'TICKET_PANEL_TITLE' = 'TICKET_PANEL_TITLE',
  'TICKET_PANEL_DESC' = 'TICKET_PANEL_DESC',
  'TICKET_PANEL_STAFF_GROUPS' = 'TICKET_PANEL_STAFF_GROUPS',
  'TICKET_PANEL_MANAGER_GROUPS' = 'TICKET_PANEL_MANAGER_GROUPS',
  'TICKET_CATEGORIES' = 'TICKET_CATEGORIES',
  'TICKET_PANEL_DROPDOWN' = 'TICKET_PANEL_DROPDOWN',
  'TICKET_PRIVATE_CATEGORIES' = 'TICKET_PRIVATE_CATEGORIES',
  'TICKET_TRANSCRIPT_CHANNEL' = 'TICKET_TRANSCRIPT_CHANNEL',
  'TICKET_MODLOG_CHANNEL' = 'TICKET_MODLOG_CHANNEL',
  'BOT_LANGUAGE' = 'BOT_LANGUAGE',
}

export enum ConfigValueType {
  'STRING' = 1,
  'BOOLEAN' = 2,
  'DECIMAL' = 3,
  'STRING[]' = 4,
}
